language: java
jdk: oraclejdk7

install: mvn clean package -P mcp-final-unix -DbuildNumber=${TRAVIS_BUILD_NUMBER}
before_script: gem install travis-artifacts
after_success:
  - export PROJECT_ARTIFACT_ID="`sed -n 's|.*<artifactId>\(.*\)</artifactId>.*|\1|p' $TRAVIS_BUILD_DIR/pom.xml | awk '{ print $1; exit }'`" && echo Project artifactId is $PROJECT_ARTIFACT_ID
  - export PROJECT_NAME="`sed -n 's|.*<name>\(.*\)</name>.*|\1|p' $TRAVIS_BUILD_DIR/pom.xml | awk '{ print $1; exit }'`" && echo Project name is $PROJECT_NAME
  - export PROJECT_VERSION="`sed -n 's|.*<version>\(.*\)</version>.*|\1|p' $TRAVIS_BUILD_DIR/pom.xml | awk '{ print $1; exit }'`" && echo Project version is $PROJECT_VERSION
  - "test ${TRAVIS_BRANCH} = master && cd $TRAVIS_BUILD_DIR/target && travis-artifacts upload --path $PROJECT_ARTIFACT_ID-* --target-path $TRAVIS_BUILD_NUMBER"
